### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jflynn129** [NordicSemiconductor/IOS-Nordic-Thingy#28]
I have cloned this repo and am currently trying to build it with the latest tools (Version 11.2.1 (11B500)).  I am using a personal account, but when I try to compile the example, it reports:

```
Build target ThingySDK_Example of project ThingySDK with configuration Debug
error: Your development team, "James Flynn", does not support the Near Field Communication Tag Reading capability. (in target 'ThingySDK_Example' from project 'ThingySDK')
error: No profiles for 'home.jflynn129.debug.IDRM' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'home.jflynn129.debug.IDRM'. (in target 'ThingySDK_Example' from project 'ThingySDK')
```
I have verified that  the info.plist contains an entry for 'Privacy - NFC Scan Usage Description' so the capability should be present.  What could be causing this issue?  Will you be updating the example to use the latest tools so that the warning are eliminated when building?

At this point, all I am trying to do is build the example application unchanged (except for the Team & Bundle Identifier) and am new to iOS App development.  Can you comment on the above question and/or provide a description of how to compile the application using the latest tools.

Thanks!

**Comment by alexisc67** [comment]
Hi, did you find the solution for this problem?

**Comment by RickvWijk1** [comment]
I'm looking for the solution as well

**Comment by soniyapatwa** [comment]
Can we test NFC using the free personal apple dev account ?

**Comment by philips77** [comment]
I'm not sure, but I don't think so. You may need Apple Developer Program to use NFC.
There was this https://developer.apple.com/forums/thread/92537 question asked 4 years ago (no replies, of course), but I assume that it didn't work on the free one.

**Comment by philips77** [comment]
Membership types comparison: https://developer.apple.com/support/compare-memberships/
