### ISSUE TITLE
README Carthage instructions error

### ISSUE THREAD

**Issue by ShortwaveRunner** [NordicSemiconductor/IOS-Nordic-Thingy#32]
The following line does not work:

github "NordicSemiconductor/NordicSemiconductor/IOS-Nordic-Thingy" ~> 1.5.0

Should probably be:

github "NordicSemiconductor/IOS-Nordic-Thingy" ~> 1.5.0

**Comment by philips77** [comment]
Of course! Thanks for pointing it!
