### ISSUE TITLE
Calibration Mode For Nordic Thingy

### ISSUE THREAD

**Issue by bkvaale** [NordicSemiconductor/IOS-Nordic-Thingy#7]
The Nordic Thingy uses a CCS 811 chip to measure CO2 & TVOC. In the CCS 811 documentation, it says the CO2 & TVOC sensors require a 48 hour period until the sensors output accurate values. Would it be possible to develop a calibration mode where the Thingy remains on for the first 48 hours when first connected to a smartphone to ensure that the CO2 & TVOC output correct values? It would be useful if the Thingy would remain on during this period even if the connection to the smartphone is lost (for example if the smartphone runs out of charge during this 48 hour period). See this [case ](https://devzone.nordicsemi.com/question/164108/nordic-thingy52-gas-sensor-readings/)for more information.

**Comment by mostafaberg** [comment]
Hi @bkvaale, This repo is for the iOS mobile app, i have referenced your issue now in the actual firmware repo so the proper person will take over from there, you can follow your issue here: https://github.com/NordicSemiconductor/Nordic-Thingy52-FW/issues/11
